//Test Data
export default {
    products: [
        {
            _id: '1',
            name: 'Hammer',
            category: 'Tools',
            description: 'Perfect for striking and pulling nails.',
            image: 'https://images.homedepot-static.com/productImages/971329b0-a9b6-4b7b-95f3-cfe28f7ac1b7/svn/dewalt-framing-hammers-dwht51064-64_1000.jpg',
            price: 26.97,
            brand: 'DEWALT',
            rating: 4.7,
            numReviews: 122,
            countInStock: 10
        },
        {
            _id: '2',
            name: 'Pliers',
            category: 'Tools',
            description: 'Durable quality, long lasting',
            image: 'https://images.homedepot-static.com/productImages/e68b77ad-0389-4dab-9c11-941977f488e0/svn/husky-all-trades-slip-joint-pliers-48020-64_1000.jpg',
            price: 8.97,
            brand: 'Husky',
            rating: 4.5,
            numReviews: 125,
            countInStock: 10
        },
        { 
            _id: '3',
            name: 'Impact Driver',
            category: 'Tools',
            description: '3 speed settings to fit any fastening need.',
            image: 'https://images.homedepot-static.com/productImages/64ce049c-d2a9-4821-a014-f8f7277c0db7/svn/ryobi-impact-drivers-p237-64_1000.jpg',
            price: 79.00,
            brand: 'RYOBI',
            rating: 4.9,
            numReviews: 1045,
            countInStock: 10
        },
        { 
            _id: '4',
            name: 'Screw Kit (675-Pack)',
            category: 'Tools',
            description: '1 in. to 2-1/2 in. Square Drive Round Head Pocket-Hole Screw Kit (675-Pack)',
            image: 'https://images.homedepot-static.com/productImages/f4aaf4f5-f92d-40d8-a1c3-a52da1cd0238/svn/kreg-self-drilling-screws-sk03-64_1000.jpg',
            price: 25.67,
            brand: 'Kreg',
            rating: 4.8,
            numReviews: 91,
            countInStock: 10
        },
        { 
            _id: '5',
            name: 'White Interior Paint',
            category: 'Paint',
            description: 'Matte sheen best for living rooms, dining rooms & bedrooms',
            image: 'https://images.homedepot-static.com/productImages/9fccc15c-18da-4ef2-995b-eb317d0a8cfd/svn/ultra-pure-white-behr-ultra-paint-colors-175004-64_1000.jpg',
            price: 14.98,
            brand: 'BEHR ULTRA',
            rating: 4.9,
            numReviews: 943,
            countInStock: 10
        },
        { 
            _id: '6',
            name: 'Flat Chip Brush',
            category: 'Paint',
            description: '2 in. angle design makes painting easier for wall-to-ceiling jobs',
            image: 'https://images.homedepot-static.com/productImages/f7ba8ccd-63fe-48f8-82ed-1416cbd587c1/svn/paint-brushes-1500-2-64_1000.jpg',
            price: 1.28,
            brand: 'Wooster',
            rating: 4.9,
            numReviews: 346,
            countInStock: 10
        },
        { 
            _id: '7',
            name: 'Roller Frame',
            category: 'Paint',
            description: 'Threaded handle end is compatible with most extension poles',
            image: 'https://images.homedepot-static.com/productImages/64dd250a-bd17-4de8-940a-80ba5fefc7c1/svn/paint-roller-frames-rf-211-9-64_1000.jpg',
            price: 4.18,
            brand: 'Wooster',
            rating: 4.2,
            numReviews: 120,
            countInStock: 10
        },
        { 
            _id: '8',
            name: 'Lawn Mower',
            category: 'Outdoor',
            description: 'Brushless Motor for Increased Run Time and Gas-Like Power',
            image: 'https://images.homedepot-static.com/productImages/164626fe-1517-4ba6-a2b5-0f3356789c59/svn/ryobi-push-lawn-mowers-ry401110-y-64_1000.jpg',
            price: 249.99,
            brand: 'RYOBI',
            rating: 4.3,
            numReviews: 3021,
            countInStock: 4
        },
        { 
            _id: '9',
            name: 'Leaf Blower',
            category: 'Outdoor',
            description: 'Turbo button for tough debris, variable trigger for precision',
            image: 'https://images.homedepot-static.com/productImages/22282e9c-8175-431b-b065-0c2034d66de7/svn/ryobi-cordless-leaf-blowers-ry40460-64_1000.jpg',
            price: 124.99,
            brand: 'RYOBI',
            rating: 4.5,
            numReviews: 3157,
            countInStock: 9
        },
        { 
            _id: '10',
            name: 'Sanded Pine Plywood',
            category: 'Building Materials',
            description: '23/32 in. x 4 ft. x 8 ft. ',
            image: 'https://images.homedepot-static.com/productImages/165e6868-4b5f-48e5-8229-10098134311a/svn/sanded-plywood-201428-64_1000.jpg',
            price: 39.99,
            brand: ' ',
            rating: 4.0,
            numReviews: 514,
            countInStock: 14
        },
        { 
            _id: '11',
            name: 'Step Ladder',
            category: 'Building Materials',
            description: 'Robust 300 lb. load capacity step ladder for maximum productivity',
            image: 'https://images.homedepot-static.com/productImages/1857e4b8-fbf2-4f2c-b162-4f24e25d8ee9/svn/werner-step-ladders-nxt1a06-64_1000.jpg',
            price: 79.99,
            brand: 'WERNER',
            rating: 4.9,
            numReviews: 514,
            countInStock: 7
        },
        { 
            _id: '12',
            name: 'Faucet',
            category: 'Appliance',
            description: 'Dorset 4 in. Centerset 2-Handle High-Arc Bathroom Faucet in Brushed Nickel',
            image: 'https://images.homedepot-static.com/productImages/a9de91ae-4c15-45f5-bf69-a5405a4947c9/svn/brushed-nickel-glacier-bay-centerset-bathroom-sink-faucets-hd67730w-6104-64_1000.jpg',
            price: 40.50,
            brand: 'Glacier Bay',
            rating: 4.5,
            numReviews: 416,
            countInStock: 200
        },
        { 
            _id: '13',
            name: '64 Gal. Trash Can',
            category: 'Cleaning',
            description: 'Easy to tilt, roll and maneuver on all terrain',
            image: 'https://images.homedepot-static.com/productImages/6f485c4a-3012-4f3e-b7c2-dc7e9d8abe7e/svn/toter-outdoor-trash-cans-79264-r2968-64_1000.jpg',
            price: 79.97,
            brand: 'Toter',
            rating: 4.5,
            numReviews: 976,
            countInStock: 154
        },
        { 
            _id: '14',
            name: 'Scrub Brush',
            category: 'Cleaning',
            description: 'Use for tough cleaning jobs at home or job site',
            image: 'https://images.homedepot-static.com/productImages/86c716d2-cbc6-4763-a7ba-2d3c9b4203ef/svn/quickie-scrub-brushes-266fg-64_1000.jpg',
            price: 16.42,
            brand: 'Quickie',
            rating: 4.7,
            numReviews: 154,
            countInStock: 71
        },
        { 
            _id: '15',
            name: '64 Gal. Trash Can',
            category: 'Cleaning',
            description: 'Easy to tilt, roll and maneuver on all terrain',
            image: 'https://images.homedepot-static.com/productImages/6f485c4a-3012-4f3e-b7c2-dc7e9d8abe7e/svn/toter-outdoor-trash-cans-79264-r2968-64_1000.jpg',
            price: 79.97,
            brand: 'Toter',
            rating: 4.5,
            numReviews: 976,
            countInStock: 154
        },
        { 
            _id: '16',
            name: 'Mango Tree',
            category: 'Fruit',
            description: 'Provides many sweet mangos for the whole family to enjoy',
            image: 'https://cgaxisimg.ams3.cdn.digitaloceanspaces.com/2018/07/cgaxis_models_105_46-03.jpg',
            price: 420.69,
            brand: 'Mother Nature',
            rating: 5.0,
            numReviews: 5,
            countInStock: 500
        },
        { 
            _id: '17',
            name: 'Built-In Side by Side Refrigerator',
            category: 'Applicances',
            description: '29.5 cu. ft. PRINTSHIELD Finish resists smudges for an enhanced look',
            image: 'https://images.homedepot-static.com/productImages/8f06710a-5ffb-481c-8d50-191c86229b5e/svn/black-stainless-with-printshield-finish-kitchenaid-side-by-side-refrigerators-kbsd608ebs-64_1000.jpg',
            price: 10599.00,
            brand: 'KitchenAid',
            rating: 4.5,
            numReviews: 147,
            countInStock: 6
        },
        { 
            _id: '18',
            name: 'Washing Machine',
            category: 'Applicances',
            description: 'Vent System prevents odors ensuring your washer is always fresh',
            image: 'https://images.homedepot-static.com/productImages/27f03b79-e78b-4642-bf6c-824dffca09b8/svn/satin-nickel-ge-front-load-washers-gfw650spnsn-64_1000.jpg',
            price: 989.00,
            brand: 'GE',
            rating: 4.8,
            numReviews: 1475,
            countInStock: 51
        },
        { 
            _id: '19',
            name: 'Gas Cooktop',
            category: 'Applicances',
            description: 'Durable metal construction for a long life and lasting use',
            image: 'https://images.homedepot-static.com/productImages/a656f8c9-6a16-4b1c-8744-e1d354916379/svn/stainless-steel-thor-kitchen-gas-cooktops-hrt3618u-64_1000.jpg',
            price: 1099.00,
            brand: 'Thor Kitchen',
            rating: 4.9,
            numReviews: 34,
            countInStock: 8
        },
        { 
            _id: '20',
            name: 'Dyson V10 Animal',
            category: 'Applicances',
            description: 'Big machine suction power. 1 But with cord-free versatility. The Dyson Cyclone V10 Animal cord-free vacuum has a 40% bigger bin than our previous Dyson V8 Animal vacuum for the big cleans.',
            image: 'https://images.homedepot-static.com/productImages/35e2563b-b2eb-49e6-bbad-c12aafa8d684/svn/dyson-stick-vacuums-343783-01-64_1000.jpg',
            price: 449.99,
            brand: 'Dyson',
            rating: 4.8,
            numReviews: 37,
            countInStock: 154
        },
        { 
            _id: '21',
            name: 'Light Bulbs',
            category: 'Lighting',
            description: '75-Watt Equivalent A19 Dimmable Eco-Incandescent Light Bulb Soft White (4-Pack)',
            image: 'https://images.homedepot-static.com/productImages/92d014e8-5071-41d6-b1a6-0014aff78f36/svn/sylvania-incandescent-light-bulbs-52603-64_1000.jpg',
            price: 6.97,
            brand: 'Sylvania',
            rating: 4.1,
            numReviews: 130,
            countInStock: 20
        },
        { 
            _id: '22',
            name: 'Industrial Storage Rack',
            category: 'Storage',
            description: 'Massive 5 ton capacity; evenly distributed at 2,500 lb. per shelf',
            image: 'https://images.homedepot-static.com/productImages/9ac55f69-558b-46ca-906b-dcd703ecc408/svn/yellow-dewalt-freestanding-shelving-units-dxst10000-64_1000.jpg',
            price: 262.78,
            brand: 'Dewalt',
            rating: 4.9,
            numReviews: 320,
            countInStock: 16
        },
        { 
            _id: '23',
            name: 'Workbench ',
            category: 'Storage',
            description: 'Includes a durable wood platform, drawer and pegboard',
            image: 'https://images.homedepot-static.com/productImages/2d1ad441-322a-4b7e-9145-9852a85c3f75/svn/husky-workbenches-g4801s-us-64_1000.jpg',
            price: 265.99,
            brand: 'Husky',
            rating: 4.5,
            numReviews: 363,
            countInStock: 14
        },
        { 
            _id: '24',
            name: '2-Door Drawer',
            category: 'Storage',
            description: 'Garage cabinet comes pre-assembled for your convenience',
            image: 'https://images.homedepot-static.com/productImages/85426c0c-821a-4c8c-a5e3-b032ae54619e/svn/glossy-black-husky-free-standing-cabinets-g2801b-us-64_1000.jpg',
            price: 167.99,
            brand: 'Husky',
            rating: 4.7,
            numReviews: 201,
            countInStock: 15
        },
        { 
            _id: '25',
            name: 'Sillcock',
            category: 'plumbing',
            description: 'Easily turn water on and off by rotating valve',
            image: 'https://images.homedepot-static.com/productImages/4aac86a9-ad5e-408c-bab8-65f8bb40bf6b/svn/everbilt-sillcocks-vscstdb3eb-64_1000.jpg',
            price: 6.44,
            brand: 'Everbilt',
            rating: 4.7,
            numReviews: 95,
            countInStock: 53
        },
        { 
            _id: '26',
            name: 'PVC Pipe',
            category: 'plumbing',
            description: 'PVC Pipe is used in gravity sewer/storm drainage applications',
            image: 'https://images.homedepot-static.com/productImages/59e06f61-372f-425d-97a2-14df93e4971d/svn/white-jm-eagle-pvc-schedule-40-pipe-1610-64_1000.jpg',
            price: 11.42,
            brand: 'JM eagle',
            rating: 4.7,
            numReviews: 163,
            countInStock: 21
        },
        { 
            _id: '27',
            name: 'Toilet',
            category: 'plumbing',
            description: 'Delivers powerful, superior performance with two flush options',
            image: 'https://images.homedepot-static.com/productImages/45d0bddb-734c-4909-87bc-4f5b99e1bc3e/svn/white-glacier-bay-one-piece-toilets-n2420-64_1000.jpg',
            price: 169.00,
            brand: 'Glacier Bay',
            rating: 4.6,
            numReviews: 1454,
            countInStock: 34
        },
        { 
            _id: '28',
            name: 'Shower Head',
            category: 'Bath',
            description: 'Easy release and return with magnetic docking',
            image: 'https://images.homedepot-static.com/productImages/60547c4e-b677-4ad0-afe1-906fc2273b2d/svn/chrome-moen-dual-shower-heads-26008-a0_1000.jpg',
            price: 79.98,
            brand: 'Moen',
            rating: 4.1,
            numReviews: 363,
            countInStock: 24
        },
        { 
            _id: '29',
            name: 'Bathroom Sinks',
            category: "bath",
            description: 'Easy to clean glazed white ceramic resists stains and scratches',
            image: 'https://images.homedepot-static.com/productImages/265653f3-015c-4ae8-bc40-a9250558bec4/svn/white-luxier-vessel-sinks-cs-013-64_1000.jpg',
            price: 67.96,
            brand: 'luxier',
            rating: 4.9,
            numReviews: 51,
            countInStock: 14
        },
        { 
            _id: '30',
            name: 'Bath Mirror',
            category: 'Bath',
            description: 'Pre-attached metal hanger mounts enable easy installation',
            image: 'https://images.homedepot-static.com/productImages/8954a07c-3f16-4570-b194-32c1f9f8193f/svn/white-home-decorators-collection-vanity-mirrors-gawm2432-64_1000.jpg',
            price: 69.90,
            brand: 'Home Decorators Collection',
            rating: 4.9,
            numReviews: 418,
            countInStock: 21
        },
    ]

};